
name: download-comics
on:
  workflow_dispatch: 
  schedule:
  # 定时任务在周六的8点执行
    - cron:  0 0 * * 6 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout actions
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install requests

    - name: Download comics
      run: python ./comics.py

    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
