
#工作名字
name: download-comics
on:
  workflow_dispatch: 
  push:
  # 当对分支master进行push操作的时候，这个工作流就被触发了
    branches: [ main ]
  pull_request:
  #只运行特定分支master
    branches: [ main ]
  schedule:
  # 定时任务在每天的14点执行
    - cron:  0 6 * * * 

jobs:
#将工作流程中运行的所有作业组合在一起
  checkin:
  #定义名为 checkin 的作业。 子键将定义作业的属性 
    runs-on: ubuntu-latest
    #将作业配置为在最新版本的 Ubuntu Linux 运行器上运行
    
    steps:
    - uses: actions/checkout@v2
    #uses 关键字指定此步骤将运行 actions/checkout 操作的 v3。 这是一个将存储
    #库签出到运行器上的操作，允许您对代码（如生成和测试工具）运行脚本或其他操
    #作。 每当工作流程将针对存储库的代码运行时，都应使用签出操作。
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1
    - name: requirements
      run: |
        python -m pip install --upgrade pip
    - name: Download
      run: |
        python3 ./comics.py 
    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
