name: trigger

on:
  schedule:
    - cron:  '30 5 * * *'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run isUpdated.sh
        env:
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
        run: |
          chmod +x scripts/isUpdated.sh
          ./scripts/isUpdated.sh "$REPO_OWNER" "$REPO_NAME"
