name: update
on:
  # 自动触发
  workflow_run:
    workflows: ["trigger"]
    types: [completed]
  
  # 手动触发
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' || 
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
    - name: Checkout actions
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install requests python-dotenv pillow

    - name: Update Student List
      env:
        REPO_OWNER: ${{ secrets.REPO_OWNER }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
      run: python scripts/momotalk.py

    - name: Update Bond Stories
      env:
        REPO_OWNER: ${{ secrets.REPO_OWNER }}
        REPO_NAME: ${{ secrets.REPO_NAME }}
      run: python scripts/bondstory.py

    - name: Update stickers
      run: python scripts/stickers.py

    - name: Commit & Push changes
      uses: Andro999b/push@v1.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
